version: "3.8"

services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - 8080:80
    volumes:
      - ./client:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/access.log:/var/log/nginx/access.log
      - ./docker/nginx/error.log:/var/log/nginx/error.log
  database:
    container_name: postgres
    image: postgres
    volumes:
      - postgre-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432 #port on host:port in container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-app}
  server:
    container_name: server
    build:
      context: ./server
      target: build-stage
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    depends_on:
      - database
    restart: always
    environment:
      - JWT_SECRET=${JWT_SECRET:-secret}
      - DATABASE_URL=${DATABASE_URL:-postgres://root:password@database:5432/app}

volumes:
  postgre-data: {}
  server: {}
  client: {}
