version: "3.8"

services:
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  database:
    container_name: postgres
    image: postgres
    volumes:
      - postgre-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432 #port on host:port in container
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app

volumes:
  mongo-data: {}
  postgre-data: {}
