version: "3.8"

services:
  client:
    container_name: client
    build:
      context: ./client
    volumes:
      - client:/app/dist
  marquesplace:
    container_name: marquesplace
    build:
      context: ./marquesplace
    volumes:
      - marquesplace:/app/dist
  database:
    container_name: postgres
    image: postgres
    volumes:
      - postgre-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432 #port on host:port in container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-app}
  server:
    container_name: server
    build:
      context: ./server
      target: build-stage
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
      - /server/node_modules
    depends_on:
      - database
    restart: always
    environment:
      - JWT_SECRET=${JWT_SECRET:-secret}
      - DATABASE_URL=${DATABASE_URL:-postgres://root:password@database:5432/app}
      - MONGO_URL=${MONGO_URL}
      - SCRAPPING_API_KEY=${SCRAPPING_API_KEY}
      - PROJECT_NAME=${PROJECT_NAME}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - MAILJET_PK=${MAILJET_PK}
      - MAILJET_SK=${MAILJET_SK}
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/access.log:/var/log/nginx/access.log
      - ./docker/nginx/error.log:/var/log/nginx/error.log
      - /etc/letsencrypt/live/kamalpay.thibautsbn.fr/fullchain.pem:/etc/pki/tls/certs/fullchain.pem
      - /etc/letsencrypt/live/kamalpay.thibautsbn.fr/privkey.pem:/etc/pki/tls/certs/privkey.pem
      - client:/var/www/client
      - marquesplace:/var/www/marquesplace
volumes:
  postgre-data: {}
  client: {}
  marquesplace: {}
