GET http://localhost:3000/

###
GET  http://localhost:3000/template/test/test
X-api-key: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZnVsbE5hbWUiOiJudWxsIG51bGwiLCJpYXQiOjE2ODc3MzAxOTUsImV4cCI6MTY4NzczMzc5NX0.MIYau-pETaeGCH3eVeOEeZBBxIfWGQjkHJv2Jh_mGlE

### 
POST http://localhost:3000/ HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "t@t.com"
}

###
GET http://localhost:3000/users
# X-api-key: 13

###
GET http://localhost:3000/users/1685116695797

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "t@tt.com"
}
### 
PUT http://localhost:3000/users/1685116695797
Content-Type: application/json

{
    "name": "John Doe",
    "email": "repalce@tt.com"
}

### 
PATCH http://localhost:3000/users/1685116695797
Content-Type: application/json

{
    "name": "John Do path",
    "email": "patchqsdft@tt.com"
}

### 
DELETE  http://localhost:3000/users/1685117275072

############
### Auth ###
############

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "email": "test1@test.com",
    "password": "password",
    "kbis": "kbis"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "thibautsembeni@gmail.com",
    "password": "password"
}

###
GET http://localhost:3000/check
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzY0LCJmdWxsTmFtZSI6IkRvZSBKb2huIiwiaWF0IjoxNjg4ODMzNjMzLCJleHAiOjE2ODg4MzcyMzN9.nzC_gToW-c2yNvbonhlk7ElOGQ8ga4hmtsQsBcy_bZw

### 
GET http://localhost:3000/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzY0LCJmdWxsTmFtZSI6IkRvZSBKb2huIiwiaWF0IjoxNjg4ODMzNjMzLCJleHAiOjE2ODg4MzcyMzN9.nzC_gToW-c2yNvbonhlk7ElOGQ8ga4hmtsQsBcy_bZw



####################
### Transactions ###
####################

GET http://localhost:3000/transactions
Content-Type: application/json

###
GET http://localhost:3000/transactions/transaction/subscribe?username=John
Accept: text/event-stream

###
POST http://localhost:3000/transactions
Content-Type: application/json

{
   "client_info": {
        "name": "Michel Chemlal le petit vieux",
        "address": "2T route de villechavant, Villebougis, 89150 France"
    },
    "billing_info": {
        "zipcode": "89100",
        "country":  "FRANCE",
        "card_type": "Visa",
        "card_bank": "Stripe Payments UK Limited",
        "card_number": "4141414141414142",
        "expiration_date": "04 / 2024",
        "cvc": true,
        "IP": "192.168.1.1",
        "device": "Ordinateur"       
    },
    "shipping_info": {
        "amount": 9,
        "costs": 10000,
        "net": 200000,
        "currency": "EUR",
        "payment_type": "Carte de crédit"
    },
    "cart": {
        "card_number": "4141414141414141"
    },
    "amount": 9,
    "currency": "EUR"
}

###
POST http://localhost:3000/transactions
Content-Type: application/json

{
    "amount": 210000.45,
    "currency": "EUR"
}


###
GET http://localhost:3000/products
Content-Type: application/json

###
GET http://localhost:3000/transactions/stats/nbbyday?date=2023-07-18
Content-Type: application/json