GET http://localhost:3000/

###
GET  http://localhost:3000/template/test/test
X-api-key: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZnVsbE5hbWUiOiJudWxsIG51bGwiLCJpYXQiOjE2ODc3MzAxOTUsImV4cCI6MTY4NzczMzc5NX0.MIYau-pETaeGCH3eVeOEeZBBxIfWGQjkHJv2Jh_mGlE

### 
POST http://localhost:3000/ HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "t@t.com"
}

###
GET http://localhost:3000/users
X-api-key: 13
###
GET http://localhost:3000/users/1685116695797

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "t@tt.com"
}
### 
PUT http://localhost:3000/users/1685116695797
Content-Type: application/json

{
    "name": "John Doe",
    "email": "repalce@tt.com"
}

### 
PATCH http://localhost:3000/users/1685116695797
Content-Type: application/json

{
    "name": "John Do path",
    "email": "patchqsdft@tt.com"
}

### 
DELETE  http://localhost:3000/users/1685117275072

############
### Auth ###
############

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "email": "test1@test.com",
    "password": "password",
    "kbis": "kbis"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "password"
}

###
GET http://localhost:3000/check
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzcyLCJmdWxsTmFtZSI6IkRvZSBKb2huIiwiaWF0IjoxNjg4ODIzMDI0LCJleHAiOjE2ODg4MjY2MjR9.hJCpN7YIbO9_BASIwOJ1iQYqwMnld3y_JC6kdUl2lak

### 
GET http://localhost:3000/verify/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzcyLCJmdWxsTmFtZSI6IkRvZSBKb2huIiwiaWF0IjoxNjg4ODIzMDI0LCJleHAiOjE2ODg4MjY2MjR9.hJCpN7YIbO9_BASIwOJ1iQYqwMnld3y_JC6kdUl2lak